version: '3'
services:
  portal-app:
    build: .
    working_dir: /usr/src/app  # üëà –£–∫–∞–∑—ã–≤–∞–µ–º, –≥–¥–µ –∏—Å–ø–æ–ª–Ω—è–µ—Ç—Å—è –∫–æ–º–∞–Ω–¥–∞ –≤–Ω—É—Ç—Ä–∏ –∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞
    volumes:
      - .:/usr/src/app         # üëà –ü–æ–¥–∫–ª—é—á–∞–µ–º –ª–æ–∫–∞–ª—å–Ω—ã–π –∫–æ–¥ –≤–Ω—É—Ç—Ä—å –∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://monty:pass@db:27017/mydb?authSource=admin&directConnection=true

  db:
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: monty
      MONGO_INITDB_ROOT_PASSWORD: pass
